plugins:
  - jekyll-feed
  - jekyll-sitemap
    #  - jekyll-seo-tag


collections:
  research:
   output: true
  theory:
   output: true
  comp:
   output: true
  linux:
   output: true
  classes:
   output: true
