markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  hard_wrap: false
  extensions: fenced_code_blocks

plugins:
  - jekyll-feed
  - jekyll-sitemap
    #  - jekyll-seo-tag


collections:
  research:
   output: true
  theory:
   output: true
  comp:
   output: true
  linux:
   output: true
  classes:
   output: true
